# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307fabc4af3e50bd833c5cc247116c029e05f83edda3b4cf70904f0b01cb2f5ad298a804bffbccb308064f9c2d83c613b081a237d732f207c864358b977eaa13

test:
  secret_key_base: 6933eef1f5336d5ba358efc1cabecd3e3545b5c31fc7bc86d3d37006ef78109a634c26f272f5cc9a30ed9a58bb9fda4eadfe12f404b45dc8cfda904c291fba81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
